version: '3'

services:
  backend:
    image: web
    build:
      context: .
      target: web
      args: &default-build-args
        PYTHON_VERSION: "3.11.7"
    environment: &default-environment
      DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      CLICKHOUSE_DATABASE_URL: clickhouse://clickuser:secret@clickhouse:9000/clickdb
      CELERY_BROKER_URL: redis://redis:6379/0
    ports:
      - 8000:8000
    depends_on: &default-depends_on
      - postgres
      - redis

  worker:
    build:
      context: .
      target: worker
      args: *default-build-args
    environment:
      <<: *default-environment
      QUEUE: celery
    depends_on: *default-depends_on

  scheduler:
    build:
      context: .
      target: scheduler
      args: *default-build-args
    environment: *default-environment
    depends_on: *default-depends_on

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    command: --autovacuum=off --fsync=off --synchronous_commit=off --full_page_writes=off --work_mem=12MB --max-connections=10 --max_wal_senders=0

  clickhouse:
    image: clickhouse/clickhouse-server:24.3.5-alpine
    environment:
      - CLICKHOUSE_DB=clickdb
      - CLICKHOUSE_USER=clickuser
      - CLICKHOUSE_PASSWORD=secret
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ports:
      - 9000:9000

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
